apiVersion: v1
kind: ConfigMap
metadata:
  name: prodman-config
  namespace: {{ .Values.namespace.name }}
data:
  DB_HOST: "postgresql"
  DB_NAME: {{ .Values.postgresql.database | quote }}
  DB_USER: {{ .Values.postgresql.username | quote }}
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"